#!/usr/bin/env php
<?php

$kahlan = 'https://raw.githubusercontent.com/crysalead/kahlan/master/composer.json';
$boxVersion = json_decode(file_get_contents($kahlan), true)['require']['crysalead/box'];

`COMPOSER_ROOT_VERSION={$boxVersion} composer install`;
